---
# tasks file for webserver
- name: Ensure nginx package is present
  apt:
    name: nginx
    state: present
- name: copy index.html
  copy: src=index.html dest={{ dest_folder }}/index.html mode=0555
  notify:
    - restart nginx
