---
- name: Installing and configuring the environment
  hosts: build_node
  become: yes

  roles:
    - common
    - build


- name: Project Launch
  hosts: app_node
  become: yes

  roles:
     - common
     - project_start