---

version: '3'
services:
    java_app:
        build:
            context: ../build_app
            dockerfile: Dockerfile
        volumes:
            - '../app/boxfuse-sample-java-war-hello:/app/boxfuse-sample-java-war-hello'
       
tomcat:
     image: tomcat:latest
     ports:
         - '8080:8080'
     volumes:
         - './usr/local/tomcat/webapps:/usr/local/tomcat/webapps'           
