---

version: '2'
services:
    java_app:
        build:
            context: ../build_app
            dockerfile: Dockerfile
        volumes:
            - '../app/boxfuse-sample-java-war-hello:/app/boxfuse-sample-java-war-hello'
        depends_on: 
            - java_app      
web:
     image: tomcat:9-jdk11
     ports:
         - '8080:8080'
     volumes:
         - './home/boxfuse-sample-java-war-hello/target/hello-1.0.war:/usr/local/tomcat/webapps'           
